version: "3.9"

services:
  note-server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - note-db
    volumes:
      - ./:/usr/note-server
    ports:
      - 8080:8080
    env_file:
      - ./.env
  note-db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
